version: "3.9"

services:
  db:
    image: postgres
    restart: always
    networks:
      - acc-backend
    environment:
      - POSTGRES_DB=book_schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
    driver: local

networks:
  acc-backend:
    driver: bridge
